---

- name: Stop opencast service on all specified hosts
  hosts:
    - allinone
  become: true
  tasks:
    - name: Stop opencast
      ansible.builtin.systemd:
        name: opencast.service
        state: stopped
        enabled: false
