---
- name: Configure Opencast User, Nginx, and Certbot on opencast hosts
  hosts: opencast
  become: true
  roles:
    - role: elan.opencast_user
    - role: elan.simple_nginx_reverse_proxy
      nginx_config:
        - src: roles/nginx_extras/templates/nginx.conf
          dest: nginx.conf
      configure_for_selinux: true
      configure_for_firewalld: true
    - role: nfs_client
    - role: elan.opencast_certbot
      opencast_certbot_letsencrypt_email: '{{ opencast_letsencrypt_email }}'
      opencast_certbot_deploy_hook: /usr/bin/systemctl reload nginx

- name: Configure PostgreSQL and Opencast user on database hosts
  hosts: database
  become: true
  roles:
    - role: elan.opencast_postgresql
    - role: elan.opencast_user
