---
- name: Configure Opencast User, Nginx, and Certbot on opencast hosts
  hosts: opencast
  become: true
  roles:
    - role: elan.opencast_user
    - role: elan.simple_nginx_reverse_proxy
      nginx_config:
        - src: roles/nginx_extras/templates/nginx.conf
          dest: nginx.conf
      configure_for_selinux: true
      configure_for_firewalld: true
    #- role: elan.elan_certbot
     # tags: certbot
    - role: nfs_client
    - role: certbot

- name: Configure PostgreSQL and Opencast user on database hosts
  hosts: database
  become: true
  roles:
    - role: elan.opencast_postgresql
    - role: elan.opencast_user
