---

- name: Install Tobira
  hosts: tobira
  become: true
  roles:
    - tobira
    - role: elan.opencast_certbot
      opencast_certbot_letsencrypt_email: '{{ opencast_letsencrypt_email }}'
      opencast_certbot_deploy_hook: /usr/bin/systemctl reload nginx
  tags: tobira
