---
- name: Restart tobira
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - tobira
    - tobira-worker

- name: Restart meili
  ansible.builtin.service:
    name: meili
    state: restarted

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
